const express = require("express");
const serviceController = require("../controllers/serviceController");
const router = express.Router();
router.post("/", serviceController.createService);
router.get("/", serviceController.getAllServices);
router.get("/:id", serviceController.getServiceById);
router.put("/:id", serviceController.updateServiceById);
router.delete("/:id", serviceController.deleteServiceById);
// router.get("/:id/details", serviceController.getServiceDetails);
module.exports = router;
